local_costmap:
  #Independent settings for the local costmap
  publish_voxel_map: true

  global_frame: odom_combined
  robot_base_frame: base_footprint

  update_frequency: 5.0
  publish_frequency: 2.0

  static_map: false
  rolling_window: true

  width: 6.0
  height: 6.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0

  # set the local costmap to allow trespassion of unknown space
  track_unknown_space: true
  unknown_threshold: 16 #9 #values >9 let costmap treat unknown space as free
